aggregation:
  title: Example of Keruu
  description: Example aggregation of posts from various RSS feeds
  maxPosts: 100

fetch:
  httpTimeout: 10s

feeds:
- name: Yle News
  url: https://feeds.yle.fi/uutiset/v1/recent.rss?publisherIds=YLE_NEWS
- name: BBC News - World
  url: http://feeds.bbci.co.uk/news/world/rss.xml
- name: Guardian
  url: https://www.theguardian.com/world/rss
- name: NPR
  url: https://feeds.npr.org/1004/rss.xml

links:
- name: reddit
  url: https://old.reddit.com/search?q=$TITLE
- name: ddg
  url: https://duckduckgo.com/?q=$TITLE

